# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'janela.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import GerarQrcode

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(602, 493)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txtNomeArquivo = QtWidgets.QLineEdit(self.centralwidget)
        self.txtNomeArquivo.setGeometry(QtCore.QRect(20, 260, 561, 22))
        self.txtNomeArquivo.setObjectName("txtNomeArquivo")
        self.btoGerar = QtWidgets.QPushButton(self.centralwidget)
        self.btoGerar.setGeometry(QtCore.QRect(240, 380, 93, 28))
        self.btoGerar.setObjectName("btoGerar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 170, 151, 16))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 561, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 240, 151, 16))
        self.label_4.setObjectName("label_4")
        self.txtPlanilha = QtWidgets.QLineEdit(self.centralwidget)
        self.txtPlanilha.setGeometry(QtCore.QRect(20, 330, 561, 22))
        self.txtPlanilha.setObjectName("txtPlanilha")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 310, 151, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 430, 561, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 80, 160, 70))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.rbDigitado = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbDigitado.setChecked(True)
        self.rbDigitado.setObjectName("rbDigitado")
        self.verticalLayout.addWidget(self.rbDigitado)
        self.rbPlanilha = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbPlanilha.setObjectName("rbPlanilha")
        self.verticalLayout.addWidget(self.rbPlanilha)
        self.txtConteudo = QtWidgets.QLineEdit(self.centralwidget)
        self.txtConteudo.setGeometry(QtCore.QRect(20, 190, 561, 31))
        self.txtConteudo.setObjectName("txtConteudo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #Botão Gerar
        self.btoGerar.clicked.connect(self.GerarCodigo)

    def GerarCodigo(self):
        conteudo = self.txtConteudo.text()
        arquivo = self.txtNomeArquivo.text()
        
        GerarQrcode.gerar(conteudo, arquivo)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GeraCode 0.1"))
        self.btoGerar.setText(_translate("MainWindow", "Gerar"))
        self.label.setText(_translate("MainWindow", "Informação do QR Code:"))
        self.label_3.setText(_translate("MainWindow", "Gerador de QR Code"))
        self.label_4.setText(_translate("MainWindow", "Nome do Arquivo:"))
        self.label_5.setText(_translate("MainWindow", "Caminho da Planilha:"))
        self.label_6.setText(_translate("MainWindow", "www.gerquali.com.br"))
        self.label_2.setText(_translate("MainWindow", "Gerar Código..."))
        self.rbDigitado.setText(_translate("MainWindow", "Conforme Digitado"))
        self.rbPlanilha.setText(_translate("MainWindow", "Baseado em Planilha"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
